language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - hhvm

install:
    - composer install --dev --prefer-dist

script:
    - mkdir -p build/logs
    - bin/phpunit -c phpunit.xml.dist --coverage-clover build/logs/clover.xml

after_success:
    - composer require "satooshi/php-coveralls:^1.0"
    - travis_retry php bin/coveralls -v
